"""Changes item model

Revision ID: 92a48a09f922
Revises: 6fc709f30248
Create Date: 2023-01-29 16:13:44.134961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a48a09f922'
down_revision = '6fc709f30248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'file')
    # ### end Alembic commands ###
